env:
  global:
  # Docker Repository
  - REPO=fjudith/draw.io
  # Compute docker tag
  - TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  # Retreive commit ID
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "SVMAZYJ/6u4maCFH+Wd7w8OYNGK6wU0EEsafNcMG1R2R6dD9dqbJGEKHjLpsCH61zRNQEVaEfPK8TjVLXWndEK5rFTdZRj6JwzEZbc1lmAZCU6zHpGHcsVOG4fRTnZGl36UUUDqttDKNwYBnJGqAK9J4IsH9KMMFmo9JhsovS+eJfKouFtZ78Q2reeSbjIxKypA9xu/k7TXBLnFM1VBJVOe/BFXHg0YawiuNM2+yudpWzviVL1ipfPYkge1r2BlelidMjnlLsa6uyjz0Lo+XvVtPkMUpiyUPEuLn935hvXvC9cy8ZRXG83f0ZU5ZQ1m6qitEDNmazBPB7egstqb+XbdM0zgLvqwPQOuawRkkf67YUOzZSYreejkzotHUtScHGDRI1JfM+M/dph7VRaRGGXIc453jHQKoWc7v6IqFR1AhSgz2eiEsUBgvmhhwYJuJ7SGsuKQpwl1QAMAr+JlLuU55pPRoOJ8Dkl10H4FNxqLbH9mZ0XZFm4hRKRtk9qQNpgWAxaC+t4EUtIKZxu5VjfWPnVwLlwyt03ke4eEV9E34jAkfFS1L5f6JkFivL/2rmG1dw815paRgHpaCaGbWRpLjgTCWV5lVy9tgYkewmY5LjOcVbRCEHM2Z3AgRrVQtxy1dlvrEZxY3jtvrpgQ91FIW8QMDGd3rB1Kxm3tb4gI="
  - secure: "WZIi3H8GGGZcA6GgUVcoJLWHjev+4tRJCbJTBkpbqoLIf8Y565plPwfAc/ez+Gt+FNm7eX5tVoneE3IHQeQaRQPeE+JdeB2AnB6TlwGXhHRR+d6bRVo3BOsyz6dRx+Qlhq7FkmzpPI30DXopG2YW1k3b4o8KthcCby9meP5EP6gjWse3SBiGfd17KWcrqWHozpEXJleW8Vf4Ldr4msOICAD0YRex4KmjVacdgaBhKx4WkM5VzF1QOWSpyY3TVnmnU1H+oWaxlG49wmC2OmMBJ+Ak+TpfH6CEftBOqNFEeHziCvFlrXIVdv+2kDtByUqZF2GmVyiWA7H74mxROAFzJpRsBpyRMStRvPgJszUfeGP7hH/nFBcBy35Dq7zQXbEd9fYzQrfNVTn0Wsfczo34YN9A/cvlpEW7RAAXcmI6T7VHvTXqkcJmmsqI/yYMHzi7vihmYLW8ck64oNKh41jPfsxfT6BGHtOohx5/BDu1UYV1Mid1+kTq2OmToO+obUdRRI9rnPd+F7jDBD8hAGsxCTYoxUfQqGRytJR7/RWOY5/Ebx2kYPgl7sUGXc+pRJrqAlw2XImjgg2hFjFxUNcxeEknu+b6ieNY1aWVC1rxkO+9cr5AYmV84L3RmIiSbmL8HMBi3B41BHJ2h/7aQf7aR0S2zRbcnp0tQGz9Fyt4zkg="
  - secure: "YWRTBvw6dXBhKqvDL5Orl3X9I2BuDSNZO3tmitugMcpYwuT/LacKcDSfveWRnhSP2sTL+ODmxbRoJwCGfTbEFf8MMXy83eH/NlzNzo5AFxxGX7VUsoVlyTI008KZPtktCt77YedvJaNG6bVMgqGpZAZ8/aXCHpUAVtOENFW9l0S/InZ9L7byCemrnHGyniapwS1wnWUalW8X0/QE9tNbEjPLVlTBVFjVIkLkBn8ACFLQDwnFB1fNtEzqBesKY4no1RUSu2HFma7glffL4g0VDF6aCvk5xA0+3rfjI8nvI5dZzapfedNRVakmDHXivooepoUzG1OU5l8gS1+1STnrw1kBul4SLBbcgTZSgwuHLU7tMHheK/zNb55GhsUF+mpWu6CVmABAkGmHzNHq+kh9iUx3BaoEwZwS9NrOsgMgaii9rPAtxgiPom/YseRg6Q3KwhJPak0/8yKA/DH6Fz8gugLmLpcL7PgRRyFSEzj5o53W9Z2aTfyFo56hB22otgvcFpHWAXyIGdhd/fXm9zInCZIJsOEGZ/wu8hFnSL6oMGMM4FG2sRNmRaRTLD5lmdlVAnZAKwqRZkjfbA0I7ijBzrPIi4J5jnLFR2iVrEwLo90E4J+2Wbeu2+ewQNJYQv0cLUjlu5mBY7FFycy9vfshaAUijOp2nJ05/8Oq4LZfiCo="

  
sudo: required
services:
  - docker


before_install:
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker run --name 'drawio' -d -p 32733:8080 -p 32734:8443 $REPO:$COMMIT
  - docker ps -a


script:
  # Wait for draw.io to start
  - sleep 10
  - docker logs drawio
  # -i, --include – include protocol headers in the output (H/F)
  # -X, --request – specify request  COMMAND (GET, PUT, DELETE…)  to use
  - docker exec drawio /bin/bash -c "curl -i http://localhost:8080"


after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO